name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Check out the child repo
      - uses: actions/checkout@v4

      # Setup Java
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and verify
        run: mvn --batch-mode clean verify
        env:
          # PAT with read: packages scope
          GITHUB_TOKEN: ${{ secrets.PARENT_PAT }}
