name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      # Step 1: Build and install java-parent
      - name: Build java-parent
        run: mvn -B clean install --file java-parent/pom.xml

      # Step 2: Build and install java-parent-boot
      - name: Build java-parent-boot
        run: mvn -B clean install --file java-parent-boot/pom.xml
      
      # Step 3: Build backend (which uses parent)
      - name: Build with Maven
        run: mvn -B verify --file pom.xml
